#!/usr/bin/env ruby

require 'socket'
require 'json'

load "#{ENV['HOME']}/.config/nautilus/save_tabs"

uri = ENV['NAUTILUS_SCRIPT_CURRENT_URI']
selected_uris = ENV['NAUTILUS_SCRIPT_SELECTED_URIS']

UNIXSocket.open(SOCKET_PATH) do |sock|
  sock.write(JSON.dump([uri, selected_uris]))
end
